services:
  - type: pserv
    name: ai-news-postgres
    env: postgres
    plan: starter
    disk:
      name: ai-news-postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  - type: cron
    name: ai-news-daily-digest
    env: python
    runtime: python
    plan: starter
    schedule: "0 9 * * *"
    buildCommand: "pip install --upgrade pip && pip install ."
    startCommand: "python -m app.database.create_tables && python main.py"
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: ai-news-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: ai-news-postgres
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: ai-news-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: ai-news-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: ai-news-postgres
          property: password
      - key: GROQ_API_KEY
        sync: false
      - key: MY_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: RECIPIENT_EMAILS
        sync: false
      - key: PROXY_USERNAME
        sync: false
      - key: PROXY_PASSWORD
        sync: false
